baseURL = "https://kropachev.digital/"
title = "kropachev.digital"
languageCode = "ru"
defaultContentLanguage = "ru"
paginate = 10
enableRobotsTXT = true
canonifyURLs    = true
enableGitInfo   = true

[sitemap]
  filename   = "sitemap.xml"
  changefreq = "weekly"
  priority   = 0.5

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[module]
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[params]
  # Два раздела контента на главной и в архивах
  mainSections = ["posts", "articles"]

[params.sidebar.avatar]
enabled = true
local   = false
src     = "https://github.com/kropachev.png?size=150"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[permalinks]
  posts = "/p/:year/:month/:slug/"
  articles = "/articles/:slug/"