baseURL = "https://kropachev.digital/"
title = "kropachev.digital"
locale = "ru"
defaultContentLanguage = "ru"

[module]
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v4"

[services.googleAnalytics]
    ID = "G-J0WLQD6BEE"

[privacy.googleAnalytics]
    respectDoNotTrack = true