mainSections = ["posts", "projects"]

[sidebar]
    emoji = ""
    subtitle = ""
    avatar = "https://github.com/kropachev.png?size=150"

[cookies]
    enabled     = true
    showSettings = true

    [cookies.categories]
        analytics  = true
        functional = true

[comments]
    enabled = false

[[widgets.homepage]]
    type = "search"

[[widgets.homepage]]
    type = "tag-cloud"
    [widgets.homepage.params]
        limit = 30

#[[widgets.homepage]]
#    type = "categories"
#    [widgets.homepage.params]
#        limit = 10

#[[widgets.homepage]]
#    type = "archives"
#    [widgets.homepage.params]
#        limit = 5

[[widgets.page]]
    type = "search"

[[widgets.page]]
    type = "toc"

#[[widgets.page]]
#    type = "tag-cloud"
#    [widgets.page.params]
#        limit = 30

#[[widgets.page]]
#    type = "categories"
#    [widgets.page.params]
#        limit = 10
