language = "ru"

[article]
  toc = true
  readingTime = true
  math = false

[article.license]
  enabled = false
  default = ""
  custom = ""

[sidebar]
  position = "right"

[[widgets.homepage]]
  type = "tag-cloud"
  [widgets.homepage.params]
    limit = 20

[[widgets.page]]
  type = "tag-cloud"
  [widgets.page.params]
    limit = 20

[[widgets.page]]
  type = "toc"